version: '3.4'

services:
  #db:
  #  restart: always
  #  image: ${DOCKER_REGISTRY-}db
  #  build:
  #    context: .
  #    dockerfile: Infrastructure/DB/Dockerfile
  #  ports:
  #    - "54322:5432"
  #  environment:
  #      POSTGRES_DB: ${POSTGRES_DB}
  #      POSTGRES_USER: ${POSTGRES_USER}
  #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  autofunnerworker:
    restart: always
    image: ${DOCKER_REGISTRY-}auto_funner_worker
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: AutoFunnerWorker/Dockerfile
    environment:
        ConnectionString: ${ConnectionString}
        DOMAIN: ${DOMAIN}
        NEW_STAGE_ID: ${NEW_STAGE_ID}
        STAGE_ID2: ${STAGE_ID2}
        API_KEY: ${API_KEY}
